Hw1. Иванцов Илья
ilyaivantsov/formal-lang-course-ivantsov pull request #1
Opened 2023-02-25 18:15 UTC by ilyaivantsov

2023-02-26 18:41 UTC, rustam-azimov requested changes

2023-02-26 18:41 UTC, rustam-azimov commented on project/graph.py
> +def graph_info(graph: nx.MultiDiGraph) -> GraphInfo:
Нужна функция, которая вернет информацию по имени графа

2023-02-26 18:41 UTC, rustam-azimov commented on project/graph.py
> +def create_two_cycles_graph(n: int, m: int, labels: tuple = ('a', 'b')) -> nx.MultiDiGraph:
И функция, которая создаст и запишет в файл такой граф

2023-02-26 20:49 UTC, ilyaivantsov commented
Добавил функции.

2023-02-27 05:38 UTC, rustam-azimov approved these changes

2023-03-01 14:56 UTC, merged